version: "3.9"

volumes:
  grafana_data: {}

networks:
  network:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Read Only Editor
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,marcusolsson-gantt-panel,grafana-worldmap-panel,briangann-gauge-panel,natel-plotly-panel

    volumes:
      - ./plg/grafana/logs:/var/log/grafana
      - ./plg/grafana/data:/var/lib/grafana
      - ./plg/grafana/provisioning:/etc/grafana/provisioning
      # - ./plg/grafana/config:/app.cfg
      # - ./plg/grafana/grafana.ini:/etc/grafana/grafana.ini
      # - ./plg/grafana/plugins:/var/lib/grafana/plugins
    restart: always
    networks:
      - network

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    restart: always
    volumes:
      - ./plg/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - ${PROMETHEUS_PORT}:9090
    networks:
      - network

  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki
    ports:
      - ${LOKI_PORT}:3100
    volumes:
      - ./plg/loki/tmp:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - network

  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION}
    container_name: promtail
    volumes:
      - ./plg/promtail/log:/var/log
      - ./plg/promtail/config/docker-config.yaml:/etc/promtail/docker-config.yaml
    restart: always
    networks:
      - network
