version: '3'
services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${USER_PASSWORD}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ../Shared/tse:/mnt
    networks:
      - databases-network

networks:
  databases-network:
    driver: bridge
    name: databases-network
