version: "3"
services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdb-${INFLUXDB_VERSION}
    ports:
      - ${INFLUXDB_PORT1}:8083
      - ${INFLUXDB_PORT2}:8086
      - ${INFLUXDB_PORT3}:8090
      - ${INFLUXDB_PORT4}:2003
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - influxdb-network

networks:
  influxdb-network:
    driver: bridge
    name: influxdb-network
