version: "3"
services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT1}:6379
    command: >
      --requirepass ${USER_PASSWORD}
    networks:
      - network

networks:
  network:
# redis-server --version
