version: '3'
services:

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${REDIS_VERSION}
    ports:
      - ${REDIS_PORT1}:6379
    networks:
    - network  

networks:
  network: 

# redis-server --version    